phases: 
  pre_build: 
    commands: 
      - echo Logging in to AWS ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build: 
    commands: 
      - echo build started on `date`
      - echo building the Docker image...
      - docker build -t graphql-api .
      - docker tag graphql-api graphql-api:latest   
  post_build: 
    commands: 
      - echo Build completed on `date`
      - echo Pushing the Docker image..
      - docker push graphql-api:latest
version: 0.1