version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to AWS ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - REPOSITORY_URI=316663644837.dkr.ecr.us-west-2.amazonaws.com/graphql-api
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
    - echo Logging in to AWS ECR...
    - aws --version
    - $(aws ecr get-login --no-include-email --region us-west-2)
    - REPOSITORY_URI=316663644837.dkr.ecr.us-west-2.amazonaws.com/graphql-api
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - IMAGE_TAG=${COMMIT_HASH:=latest}
  post_build:
    commands: 
      - echo Build completed on `date`
      - echo Pushing the Docker image..
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"graphql-api","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json